version: "3.8"

services:
  web:
    build: .
    restart: always
    container_name: "libreddit"
    ports:
      - 8020:8020
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--tries=1", "http://localhost:8020/settings"]
      interval: 5m
      timeout: 3s
